### ISSUE TITLE
Control no visible

### ISSUE THREAD

**Issue by shaymongracia** [royben/RealTimeGraphX#1]
Hello,

I don't know if I'm doing something wrong!!! but the controller is not visible in my Window.xaml

I used the sample code in RealTimeGraphX.WPF.Demo and use the exact same code...

![no_show](https://user-images.githubusercontent.com/46830506/54950665-c170a700-4f0f-11e9-8c2a-6e0229313fa5.png)

this is my MainWindow.xaml
`<Window x:Class="pwr_supply.Views.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ctrl="clr-namespace:pwr_supply.Views.Controls"
        xmlns:collections="clr-namespace:System.Collections;assembly=mscorlib"
        xmlns:local="clr-namespace:pwr_supply"
        mc:Ignorable="d"
        Title="RealtimeDemo" Height="720" Width="1280" FontFamily="Consolas" FontSize="14" d:DataContext="{d:DesignData Type=local:MainWindowVM, IsDesignTimeCreatable=False}">
    
    
    <Window.Resources>
        <collections:ArrayList x:Key="colors">
            <Color>DodgerBlue</Color>
            <Color>Red</Color>
            <Color>Green</Color>
        </collections:ArrayList>

        <collections:ArrayList x:Key="brushes">
            <SolidColorBrush Color="Transparent"></SolidColorBrush>
            <SolidColorBrush Color="#861E90FF"></SolidColorBrush>
            <LinearGradientBrush>
                <GradientStop Offset="0" Color="#86FF0000" />
                <GradientStop Offset="1" Color="#80FFFF00" />
            </LinearGradientBrush>
        </collections:ArrayList>

    </Window.Resources>

    <Grid x:Name="mainGrid">

        <Grid.RowDefinitions>
            <RowDefinition Height="100"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>

        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>

        <Border Grid.Row="1" Grid.Column="0" CornerRadius="5" BorderBrush="Black" Padding="5" BorderThickness="1" Margin="5">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="200"/>
                </Grid.ColumnDefinitions>

                <ctrl:GraphController Grid.Row="0" Grid.Column="0" Controller="{Binding GraphController, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Margin="0 0 5 0"/>

                <Border Grid.Row="0" Grid.Column="1" BorderBrush="Black" BorderThickness="1" CornerRadius="5" Padding="5">
                    <StackPanel Orientation="Vertical">
                        <TextBlock >Duration</TextBlock>
                        <TextBox Margin="0 5 0 0" Text="{Binding GraphController.Range.MaximumX,Mode=TwoWay}"></TextBox>

                        <TextBlock  Margin="0 10 0 0">Refresh Rate</TextBlock>
                        <TextBox Margin="0 5 0 0" Text="{Binding GraphController.RefreshRate,Mode=TwoWay}"></TextBox>

                        <TextBlock  Margin="0 10 0 0">Minimum Y</TextBlock>
                        <TextBox Margin="0 5 0 0" Text="{Binding GraphController.Range.MinimumY,Mode=TwoWay}"></TextBox>

                        <TextBlock  Margin="0 10 0 0">Maximum Y</TextBlock>
                        <TextBox Margin="0 5 0 0" Text="{Binding GraphController.Range.MaximumY,Mode=TwoWay}"></TextBox>

                        <CheckBox Margin="0 5 0 0" IsChecked="{Binding GraphController.Range.AutoY,Mode=TwoWay}">Auto Range (Y)</CheckBox>

                        <TextBlock  Margin="0 20 0 0">Stroke</TextBlock>
                        <ComboBox Margin="0 5 0 0" ItemsSource="{StaticResource colors}" SelectedItem="{Binding Controller.DataSeriesCollection[0].Stroke}"/>

                        <TextBlock  Margin="0 10 0 0">Thickness</TextBlock>
                        <Slider Margin="0 5 0 0" Minimum="1" Maximum="5" Value="{Binding GraphController.DataSeriesCollection[0].StrokeThickness}" IsSnapToTickEnabled="True" TickFrequency="1" />

                        <TextBlock  Margin="0 10 0 0">Fill</TextBlock>
                        <ComboBox Margin="0 5 0 0" ItemsSource="{StaticResource brushes}" SelectedItem="{Binding Controller.DataSeriesCollection[0].Fill}"/>

                        <CheckBox Margin="0 10 0 0" IsChecked="{Binding GraphController.IsPaused,Mode=TwoWay}">Paused</CheckBox>

                        <Button Margin="0 10 0 0" Padding="5" Command="{Binding GraphController.ClearCommand}">Clear</Button>

                        <TextBlock  Margin="0 10 0 0">DataSeries Count</TextBlock>
                        <TextBox Text="{Binding GraphController.DataSeriesCollection.Count, Mode=OneWay}"/>
                    </StackPanel>
                </Border>

            </Grid>
        </Border>

    </Grid>
</Window>`

my ViewModel

`public class MainWindow : Helpers.PropertyChangedNotification
    {

        #region Constructors

        public MainWindow()
        {
            GraphController = new WpfGraphController<TimeSpanDataPoint, DoubleDataPoint>();
            GraphController.Range.MinimumY = 0;
            GraphController.Range.MaximumY = 3000;
            GraphController.Range.MaximumX = TimeSpan.FromSeconds(10);
            GraphController.Range.AutoY = false;

            GraphController.DataSeriesCollection.Add(new WpfGraphDataSeries()
            {
                Name = "SM-G9600_POWER_ON",
                Stroke = Colors.DodgerBlue,
                Fill = Brushes.Transparent,
                IsVisible = true,
            });

            dumyData();
        }

        #endregion Constructors

        #region Fields

        Random rd = new Random();

        #endregion Fields

        #region Properties

        public WpfGraphController<TimeSpanDataPoint, DoubleDataPoint> GraphController { get { return GetValue(() => GraphController); } set { SetValue(() => GraphController, value); } }
        

        #endregion Properties

        #region Private Methods

        void dumyData()
        {
            Stopwatch watch = new Stopwatch();
            watch.Start();

            Task.Factory.StartNew(() =>
            {
                while (true)
                {
                    var y = rd.NextDouble() * 3000;
                    var x = watch.Elapsed;

                    GraphController.PushData(x, y);

                    Thread.Sleep(30);
                }
            });
        }

        #endregion Private Methods

        #region Public Methods

        #endregion Public Methods

    }`

Here are all files and solution I'm using... 
[https://mega.nz/#!cJwDxAYa!1y06JZmGTp54c9o-tr3yilHV94FnPdIsjsQ3LOwh0kg](url)

**Comment by royben** [comment]
Use WpfGraphSurface, not GraphController for displaying the graph. Please follow the example project, you should be fine.

**Comment by Louis5756** [comment]
Hi,
Have the same situation cannot see graphic.
I cannot see in the example of the project (WPF.demo) where you are using WPFGraphSurface.
Thank you for your response.
Best regards.
