### ISSUE TITLE
Marker and Multi YAxis avaible

### ISSUE THREAD

**Issue by philipphagen87** [royben/RealTimeGraphX#10]
Hi!

I "played" a little bit with this cool graph, but this two features I didn't found...
Is a marker avaible or is it possible to implement it?
Same question for Multi Y-Axis...

greetings Phil

**Comment by philipphagen87** [comment]
I hope i can do that with a picture
![image](https://user-images.githubusercontent.com/43008517/92528361-eef70080-f228-11ea-93ab-4f1ccf221e2a.png)


green and violett are two axis with x values, the red line is a marker and the marker returns the values of each axis

**Comment by royben** [comment]
Since your request is to draw the marker in an absolute position, there is no need to implement this from within the library.
You can easily draw a movable line using standard WPF controls.
