### ISSUE TITLE
Clear graph when paused not clearing surface

### ISSUE THREAD

**Issue by Shkolik** [royben/RealTimeGraphX#12]
Found one issue with clearing, easy reproducible on your example project.

When we stop pushing any data to the controller and call ClearCommand your code clears datapoints collection, but not re-render graph. 

To reproduce replace `while (true)` Line 76 MainWindowVM with `while (!Controller.IsPaused)`.

This issue has very simple workaround, tho. After calling ClearCommand I just added one data point with default values, like `Controller.ClearCommand.Execute(null);
Controller.PushData(new Int32DataPoint(0), new Int32DataPoint(0));`

But still, it will be great to fix this issue.

PS: Great library! If it be easy to implement tooltips for points on a graph, or 'marker line', like was mentioned on #10, it will be 100% match to my use case. If you have an idea how to do it, at least direction, will be appreciated!

**Comment by royben** [comment]
- Improved clear support.
- Added support for tooltips. (see the latest demos)
