### ISSUE TITLE
X axis range problems

### ISSUE THREAD

**Issue by SzerencsesDenes** [royben/RealTimeGraphX#14]
Hi!

I have issues with the Controller.Range.MaximumX property. The controller is a WpfGraphController<FloatDataPoint, FloatDataPoint> and i set this property to 25 based on the demo provided by you. As a little test i have pushed a 100 data, one by one, throught Controller.PushData(X,Y) and at the end the number of displayed points is a 100 instead of the top 25 which should be the case, as the MaximumX property is still 25.

Any Guess why i see all my data instead of the last few entries?

**Comment by royben** [comment]
I found an issue with the FloatDataPoint.
Please get the latest version and try again.

**Comment by SzerencsesDenes** [comment]
It seems to be working now.
One more thing, the "zooming" does not work, in previous versions it showed me a conversion error (single - double), now it's just not working with the ctrl+click and drag .
Also i want to clear the graph from code behind, is it possible to force render a clear graph after i called controller.clear().
