### ISSUE TITLE
[UWP] Labels in X and Y axis do not appear in release mode

### ISSUE THREAD

**Issue by aliartinis** [royben/RealTimeGraphX#15]
Hey Roy,
When launching the demo app in release, the X and Y axis values do not appear.

Moreover, in the console there are a bunch of these:
![image](https://user-images.githubusercontent.com/83579359/116859884-fa0c0000-ac00-11eb-9389-1ac9542f9f73.png)

**Comment by royben** [comment]
It seems like an issue with native tool chain compilation on "Release" mode.
Please get the latest version and try again.

**Comment by aliartinis** [comment]
It works. However when deploying apps I read it is necessary to compile with the native toolchain.

**Comment by royben** [comment]
For all I know, .net native only tries to bring some performance optimization.

**Comment by guillemonzo** [comment]
Hi, this happens to me also, even disabling the native toolchain compilation. 

![image](https://user-images.githubusercontent.com/12409570/155717556-d0e6b2cd-5bf7-4bcd-a07e-94e5c3cf6289.png)

@aliartinis how did you make it work? Any ideas?

**Comment by aliartinis** [comment]
Edit Default.rd.xml (your project directory > Properties) and add `<Type Name="Windows.UI.Xaml.Controls.TextBlock" Dynamic="Required Public" />`  before `</Application>`. Hope it works for you.

**Comment by guillemonzo** [comment]
Hello @aliartinis, thank you so much for the answer but it didn't work :(

I'm new to UWP development and I'm not sure about what it's going on in order to tackle the problem.

Maybe it is a binding issue? I was wondering why any of the components of the library uses code-behind. All the XAML for the different components is located under the `Themes\Generic.xaml` file, so there is no possibility to use `{x:Bind}`.

**Comment by aliartinis** [comment]
Hey, sorry it wasn't the answer to your issue but then I guess it is a different one. In your screenshot you even don't have the curves drawn when it supposed to? It may be easier if you have some project or piece of code that we can look at.

> I was wondering why any of the components of the library uses code-behind.

Those are made as templated custom controls and the XAML part has to be in that Generic.xaml. The binding is then only possible using TemplateBinding or Binding (with some subtle detail). You can try make one yourself to get more familiarity by adding a new item and selecting "Templated Control".

**Comment by guillemonzo** [comment]
Hi @aliartinis thanks for your time and for helping me out.

The purpouse of the screnshot was to display the issue with the axis, the series are drawn correctly when the user hits the "Play" button. However, only the X axis gets updated:

![image](https://user-images.githubusercontent.com/12409570/156131140-1aa0dd86-ea61-410a-80c9-b5f315ece159.png)

The thing is that it happens sometimes. I have added navigation to the app (using [Windows Template Studio](https://marketplace.visualstudio.com/items?itemName=WASTeamAccount.WindowsTemplateStudio)) and if I navigate back and forth, sometimes the chart is completely loaded and sometimes not.

As you experienced, the demo app reproduces a similar behaviour on the MultiSeries example, but after a few seconds it is compleated loaded:

![image](https://user-images.githubusercontent.com/12409570/156132013-781fbf9b-cf0f-4f20-a60a-b33085f305fe.png)

I've created a [gist](https://gist.github.com/guillemonzo/e49997b1a2751a9b4c7ebf8cd7b010df) so you can have more context but I think is something related to the RealTimeGraphX library. It is like the `UwpBindingElement` on the [Generic.xaml](https://github.com/royben/RealTimeGraphX/blob/d35b95d65ee118450c4dbafd61b90c14a9067bd0/RealTimeGraphX.UWP/Themes/Generic.xaml#L52) is not getting updated.

Thanks again for your help, I appreciate it.

**Comment by aliartinis** [comment]
Ah I see, this is then different from the issue I faced. I guess you will need to go the source code of the library and find a way.

**Comment by guillemonzo** [comment]
@royben any idea on this?
