### ISSUE TITLE
How to perform zooming and panning actions?

### ISSUE THREAD

**Issue by Gary-Ge** [royben/RealTimeGraphX#16]
Thank you for writing this high performance plotting library.
I find the **zooming and panning** feature description on README, but do not know how to use it. Could you please give an example to show how to use this feature?

**Comment by royben** [comment]
Left Ctrl + mouse drag.

**Comment by Gary-Ge** [comment]
> Left Ctrl + mouse drag.

Thank you, works like a charm!
