### ISSUE TITLE
different decimal places for some charts.

### ISSUE THREAD

**Issue by edward-jang** [royben/RealTimeGraphX#18]
I use multi charts in my program, which has datagrid.
When I click some row, i want to show some chart with RealtimeGraphX.

In my case, the chart's y axis's string format are different because of  decimal places respectively.
For row1, I need "F4".           ex) 0.3333
For row2, I need "F0". (integer) ex) 3000
For row3, I need "F1" .              ex) 3.5

My program skill is not good..
I set string format in View.xaml as following.
      <realTimeGraphX:WpfGraphAxisControl Orientation="Vertical" Controller="{Binding Controller}" StringFormat="####.####" />
Then it's only for "F4" decimal places.
Please help me for my issue.

**Comment by royben** [comment]
You need to bind the "StringFormat" value to a property of your row's object.

Let's say your row is represented by an object:

ChartViewVM.cs

String Name = "Chart1";
String StringFormat = "0.0000";

Your programming skills are not so relevant as your familiarity with the WPF framework and MVVM design patterns.
You can send me an example project and I will try to help you.

**Comment by edward-jang** [comment]
I tried to make simple example. But I failed to make it.
Your component(RealtimeGraphX) is very large and complex component for me....
AndI have a little binding concept, so I can't understand what you said..
I don't know how to bind WpfGraphAxisControl and WpfGraphControl in Generic.Xaml in RealtimeGraphX.WPF.Demo.

Please add a button to change the StringFormat(0.0000)  in your application(WPF.demo), which has the stringformat (0.0).
Please help me.

**Comment by royben** [comment]
Check out the latest code on "master".
The WPF demo now contains an example tab for a list binding.

**Comment by edward-jang** [comment]
Thank you very much....
