### ISSUE TITLE
How to display y-Axis values with more decimal digit ?

### ISSUE THREAD

**Issue by ctargat** [royben/RealTimeGraphX#21]
Hi,
Thanks for your fantastic and performant library.

I would like to know how to extend the display of the number of decimal digit on the Y-Axis.
I'm working with some values which need more precision in the display (ideally 3 digits after the dot)
By default, only one decimal digit is displayed.
Any Clue ?

Thanks

**Comment by royben** [comment]
There WPF demo includes a decimal place change.
