### ISSUE TITLE
Migrating WPF to .NET  (core)

### ISSUE THREAD

**Issue by raffaeler** [royben/RealTimeGraphX#22]
I migrated the library and the process was straightforward:
- Created a new .NET WPF project
- Added a reference to the `System.Drawing.Common`
- Copied all the file from the WPF project to this new one 

The significant part of the csproj is:
```
    <PropertyGroup>
        <TargetFramework>net5.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <RootNamespace>RealTimeGraphX.WPF</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Drawing.Common" Version="5.0.2" />
    </ItemGroup>
```
The source files can be instead be put in a "Shared Project" so that you can create separate binary files (.NET Framework and .NET) from the same sources.

Questions:
- are you willing to do it in order to get the nuget packages instead of building the libs manually?
- Is this repo still under maintenance?

Thanks!

**Comment by GGorany** [comment]
I migrated this project the way you pointed out.
However, the graph is not displayed.
just a white screen.
I am a beginner in programming. so, I would be grateful if you could help me.
I share a sample project here.

[RealTimeGraphX-master.zip](https://github.com/royben/RealTimeGraphX/files/7800971/RealTimeGraphX-master.zip)

**Comment by raffaeler** [comment]
Hi @GGorany 
Given that nobody answered after months, I strongly suggest you to adopt a different library.
I found other issues in the chart control and had to modify it to refresh the surface that otherwise showed the old data.
Anyway, the changes above are enough to see something on screen. Ensure you didn't make any other changes before trying anything else.

**Comment by GGorany** [comment]
Thanks for your advice.
I will try another library.
thank you.
