### ISSUE TITLE
Why it WpfGraphControl not defined in RealTimeGraphX.WPF ?

### ISSUE THREAD

**Issue by PhilJollans** [royben/RealTimeGraphX#25]
The control **WpfGraphControl** is defined in the project **RealTimeGraphX.WPF.Demo**, along with the associated control template in Generic.xaml.

Why is this control not defined in the project **RealTimeGraphX.WPF** instead of the demo project. 
In my opinion this is core part of the control.

**Comment by royben** [comment]
Actually it's not.
WpfGraphControl is just a demonstration of using the core components.
