### ISSUE TITLE
Have you considered adding a caption to the Axes?

### ISSUE THREAD

**Issue by PhilJollans** [royben/RealTimeGraphX#26]
In my application I am showing a voltage signal in the unit V.

In my opinion it is critical to show what the signal is, and most important, what the unit it. For example, I will probably add the caption "Sensor Voltage [V]".

It's less important on the horizontal axis, because this is pretty obviously Time, but if there was a Caption property, it should obviously be supported on both axes.

Obviously, I could add a label to the left of the Graph. 
I could probably also implement it with an "Attached Property" and a modified control template.

However. I think it would be better to make it property of the Axis and display it with the axis using the same font and color.  
(I will probably try to implement this on my fork of the repository.)

**Comment by royben** [comment]
It will be totally redundant to implement as part of the library.
