### ISSUE TITLE
Any suggestions on how to add start button and reset button to the demo?

### ISSUE THREAD

**Issue by SoeLinPaing** [royben/RealTimeGraphX#6]

**Comment by dmedine** [comment]
The thread that polls the cursor position and adds the data to the chart is launched from the MainWindowVM constructor: https://github.com/royben/RealTimeGraphX/blob/master/RealTimeGraphX.WPF.Demo/MainWindowVM.cs#L74. You would have to move the thread management into its own method and then hook that up to a control in the GUI.
