### ISSUE TITLE
Howto Map data?

### ISSUE THREAD

**Issue by philipphagen87** [royben/RealTimeGraphX#9]
Hi! Is there a implemented Data mapper?

I have a ObservableCollection<ValueModel> _actValue
and the ValueModel contains:
        public DateTime _dateTime;
        public double _value;

I add every 1ms one datapoint. is it possible to map the data?

thanks ### Philipp

**Comment by royben** [comment]
1. It is unlikely that you are adding a data point every 1 millisecond. The runtime engine is just not that accurate.
2. I don't think that DateTime even supports 1 millisecond resolution.

you should prepare your data in the form of two lists.
one of type TimeSpan and one of type double.
they need to be equal in length.
Then push them into the controller.

**Comment by philipphagen87** [comment]
Thanks for the answer..
